#!/usr/bin/env python3
"""Generates src/assets/GameTables.inc from a checkout of https://github.com/wanda-phi/pfr.

pfr's authors gave permission to reuse their work. Its asset extraction contains long
per-table lookup tables (handler addresses, script opcodes, effects, bindings); copying
them mechanically avoids transcription mistakes. Logic is translated by hand elsewhere.

usage: gen_game_tables.py <checkout> <output.inc>
"""
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
out_path = Path(sys.argv[2])
src = {p: (root / 'src' / p).read_text() for p in [
    'assets/table/physics.rs', 'assets/table/script.rs', 'assets/table/sound.rs',
    'assets/table/lights.rs']}
out = ['// Generated by tools/gen_pfr_tables.py from wanda-phi/pfr. Do not edit.', '']


def enum_variants(text, name):
    m = re.search(r'enum ' + name + r' \{(.*?)\n\}', text, re.S)
    body = re.sub(r'\([^()]*\)', '', re.sub(r'//[^\n]*', '', m.group(1)))
    return [re.match(r'\s*(\w+)', v).group(1) for v in body.split(',') if v.strip()]


def emit_enum(text, name, cpp_name=None):
    vs = enum_variants(text, name)
    cpp_name = cpp_name or name
    out.append(f'enum class {cpp_name} : u16 {{ ' + ', '.join(vs) + ', Count };')
    out.append(f'inline constexpr const char* k{cpp_name}Names[] = {{ ' +
               ', '.join(f'"{v}"' for v in vs) + ' };')
    out.append('')


def fn_body(text, name):
    start = text.index('fn ' + name)
    depth, i = 0, text.index('{', start)
    for j in range(i, len(text)):
        if text[j] == '{': depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0: return text[i:j]
    raise ValueError(name)


def per_table(body):
    """Splits a body at `TableId::TableN =>` markers."""
    parts = re.split(r'TableId::Table(\d) =>', body)
    return [(int(parts[k]) - 1, parts[k + 1]) for k in range(1, len(parts), 2)]


def arms(text):
    """`0xA | 0xB => Enum::Variant(args),` -> [(ptrs, variant, args)]"""
    res = []
    for m in re.finditer(r'((?:0x[0-9a-fA-F]+\s*\|\s*)*0x[0-9a-fA-F]+)\s*=>\s*\{?\s*(?:Some\()?\s*\w+::(\w+)(?:\(([^()]*(?:\([^()]*\))?[^()]*)\))?', text):
        ptrs = [int(p, 16) for p in re.findall(r'0x[0-9a-fA-F]+', m.group(1))]
        res.append((ptrs, m.group(2), (m.group(3) or '').strip()))
    return res


phys, script, sound, lights = (src[k] for k in ['assets/table/physics.rs', 'assets/table/script.rs',
                                                'assets/table/sound.rs', 'assets/table/lights.rs'])
for n in ['HitTrigger', 'RollTrigger', 'PhysmapBind']: emit_enum(phys, n)
for n in ['JingleBind', 'SfxBind']: emit_enum(sound, n)
emit_enum(lights, 'LightBind')
for n in ['ScriptBind', 'EffectBind', 'ScriptScore', 'CheatEffect']: emit_enum(script, n)
emit_enum(script, 'UopKind')

# Trigger handler addresses.
for fn, kind in [('extract_roll_trigger_list', 'RollTrigger'), ('extract_hit_triggers', 'HitTrigger')]:
    out.append(f'struct {kind}Handler {{ u8 table; u16 ptr; {kind} kind; u8 arg; }};')
    out.append(f'inline constexpr {kind}Handler k{kind}Handlers[] = {{')
    for t, body in per_table(fn_body(phys, fn)):
        for ptrs, v, a in arms(body):
            for p in ptrs: out.append(f'  {{{t}, 0x{p:04x}, {kind}::{v}, {a or 0}}},')
    out.append('};\n')

# Script opcodes.
out.append('struct UopHandler { u8 table; u16 ptr; UopKind kind; DmFont font; bool centered; };')
out.append('inline constexpr UopHandler kUopHandlers[] = {')
for t, body in per_table(fn_body(script, 'xlat_uop_kind')):
    for ptrs, v, a in arms(body):
        args = [x.strip() for x in a.split(',')] if a else []
        font = args[0] if args else 'DmFont::H13'
        centered = args[1] if len(args) > 1 else 'false'
        for p in ptrs: out.append(f'  {{{t}, 0x{p:04x}, UopKind::{v}, {font}, {centered}}},')
out.append('};\n')

# Score references.
out.append('struct ScoreRef { u8 table; u16 ptr; ScriptScore kind; u8 arg; };')
out.append('inline constexpr ScoreRef kScoreRefs[] = {')
for t, body in per_table(fn_body(script, 'xlat_score')):
    for ptrs, v, a in arms(body):
        arg = a if re.fullmatch(r'\d+', a or '') else '0'
        for p in ptrs: out.append(f'  {{{t}, 0x{p:04x}, ScriptScore::{v}, {arg}}},')
out.append('};\n')

# Script ranges.
out.append('struct ScriptRange { u8 table; u16 begin, end; };')
out.append('inline constexpr ScriptRange kScriptRanges[] = {')
for t, body in per_table(fn_body(script, 'extract_scripts').split('let mut msgs')[0]):
    for b, e in re.findall(r'\((0x[0-9a-f]+),\s*(0x[0-9a-f]+)\)', body):
        out.append(f'  {{{t}, {b}, {e}}},')
out.append('};\n')

# Script binds.
out.append('struct ScriptBindAddr { u8 table; ScriptBind bind; u16 addr; };')
out.append('inline constexpr ScriptBindAddr kScriptBinds[] = {')
for t, body in per_table(fn_body(script, 'extract_script_binds')):
    for v, a in re.findall(r'ScriptBind::(\w+)\s*=>\s*Some\((0x[0-9a-f]+)\)', body):
        out.append(f'  {{{t}, ScriptBind::{v}, {a}}},')
out.append('};\n')

# Cheats: addresses per table, in the order of the Rust tuple.
body = fn_body(script, 'extract_cheats')
names = re.search(r'let \((.*?)\) = match', body, re.S).group(1)
names = [n.strip() for n in names.split(',') if n.strip()]
out.append('struct CheatAddrs { u16 ' + ', '.join(names) + '; };')
out.append('inline constexpr CheatAddrs kCheatAddrs[4] = {')
for t, part in per_table(body.split('.into_iter()')[0].split('= match table')[1]):
    vals = re.findall(r'0x[0-9a-f]+', part)
    if vals: out.append('  {' + ', '.join(vals) + '},')
out.append('};\n')

# Effects.
out.append('struct EffectAddr { u8 table; u16 addr; EffectBind bind; };')
out.append('inline constexpr EffectAddr kEffectAddrs[] = {')
for t, body in per_table(fn_body(script, 'extract_effects')):
    for a, v in re.findall(r'\((0x[0-9a-f]+),\s*EffectBind::(\w+)\)', body):
        out.append(f'  {{{t}, {a}, EffectBind::{v}}},')
out.append('};\n')

# Sound binds.
for fn, kind in [('extract_jingle_binds', 'JingleBind'), ('extract_sfx_binds', 'SfxBind')]:
    out.append(f'struct {kind}Addr {{ u8 table; {kind} bind; u16 addr; }};')
    out.append(f'inline constexpr {kind}Addr k{kind}Addrs[] = {{')
    for t, body in per_table(fn_body(sound, fn)):
        for v, a in re.findall(kind + r'::(\w+)\s*=>\s*Some\((0x[0-9a-f]+)\)', body):
            out.append(f'  {{{t}, {kind}::{v}, {a}}},')
    out.append('};\n')

# Light binds (1-based light numbers, as in pfr's source).
out.append('struct LightBindSet { u8 table; LightBind bind; std::initializer_list<u8> lights; };')
out.append('inline const LightBindSet kLightBinds[] = {')
for t, body in per_table(fn_body(lights, 'extract_light_binds').split('let mut res')[0]):
    for v, ls in re.findall(r'\(\s*LightBind::(\w+),\s*&\[([^\]]*)\]', body):
        out.append(f'  {{{t}, LightBind::{v}, {{{ls.strip().rstrip(",")}}}}},')
out.append('};\n')

# The IBM CGA 8x8 font the menu's left panel uses.
intro = (root / 'src' / 'assets' / 'intro.rs').read_text()
rows = re.findall(r'\[((?:0x[0-9a-f]{2},\s*){7}0x[0-9a-f]{2})\]', intro.split('CGA_FONT')[1])
assert len(rows) == 0x80, len(rows)
out.append('inline constexpr u8 kCgaFont[0x80][8] = {')
for r in rows: out.append('  {' + r + '},')
out.append('};\n')

out_path.write_text('\n'.join(out) + '\n')
print(f'wrote {out_path} ({len(out)} lines)')
