#!/usr/bin/env python3
"""mkappicon.py <icon.png> <out.h> -- the window's icon, compiled into the program.

The taskbar and the window list take their icon from the window itself on Linux and Windows,
so a small copy of assets/app/icon.png is carried in the binary as RGBA pixels, with nothing
to find beside it at run time. Generated once and committed, like the Windows .ico, so no
image tooling has to exist on the runners; the downscale is mkico.py's.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from mkico import box, read_png  # noqa: E402

SIZE = 128

src, out = sys.argv[1], sys.argv[2]
img, w, h = read_png(src)
assert w == h, "icon must be square"
px = box(img, w, h, SIZE)
rows = []
for i in range(0, len(px), 32):
    rows.append("  " + ",".join(str(b) for b in px[i:i + 32]) + ",")
Path(out).write_text(
    "#pragma once\n"
    "// Generated by tools/mkappicon.py from assets/app/icon.png -- do not edit.\n"
    "// The window's own icon, for the taskbar and the window list on Linux and Windows.\n"
    "#include <cstdint>\n\n"
    "namespace encore {\n\n"
    f"inline constexpr int kAppIconSize = {SIZE};\n"
    f"inline constexpr std::uint8_t kAppIcon[{SIZE * SIZE * 4}] = {{\n"
    + "\n".join(rows) + "\n};\n\n"
    "}  // namespace encore\n")
print(f"{out}: {SIZE}x{SIZE} RGBA, {len(px)} bytes")
